### ISSUE TITLE
Publish new release to NPM

### ISSUE THREAD

**Issue by lucasfeliciano** [FuYaoDe/react-native-app-intro#11]
Hello there :D

So, I saw that you fixed that issue about the triggering the callback when the animation start but I think you forgot to publish it into NPM, it still the old version :)

**Comment by paulohenriquesg** [comment]
+1

**Comment by FuYaoDe** [comment]
Sorry and thank you for your patience.
This is my first module in npm publish 😄 
Always forget to update...
