### ISSUE TITLE
Level Swipe doesn´t work if Dev mode: off

### ISSUE THREAD

**Issue by StellwagJo** [FuYaoDe/react-native-app-intro#13]
As far as my Dev mode is set to on the different level at a swipe work perfect. As far as I set Dev mode: off its complete static at the swipe. (Using: Samsung Galaxy Note Edge 2 - Android: 6.0.1) (React-Native: 0.23.1)

**Comment by FuYaoDe** [comment]
I'm in the simulator is normal. i don't have the physical machine, have the opportunity to help you test, it is theoretically capable of functioning.

**Comment by k0d** [comment]
I also have this issue, iPhone 6, iOS 9

**Comment by MichaelHancock** [comment]
I have this issue as well. But let me be clear, when running on the device using Xcode and in development mode; it works fine. Problems only occur upon release.

**Comment by fiattt** [comment]
same issue  iPhone6,iOS9

**Comment by fiattt** [comment]
test demo in iOS simulator(9.3) is not work too.  "dev=true" is fine.  "dev=false" is not work

change

jsCodeLocation = [NSURL URLWithString:@"http://127.0.0.1:8081/index.ios.bundle?platform=ios&dev=true"];

to 

jsCodeLocation = [NSURL URLWithString:@"http://127.0.0.1:8081/index.ios.bundle?platform=ios&dev=false"];

**Comment by mmoutenot** [comment]
I'm experiencing this as well. Trying to do some testing with a physical device but haven't found anything obvious yet...

**Comment by mmoutenot** [comment]
I can echo that it works with a physical device as well, as long as the build is non-release.

**Comment by mmoutenot** [comment]
`        if (node.type.displayName === 'View') {
          element = this.renderChild(node, pageIndex, `${index}_${i}`);
        }
`

is the problem. I bet that displayName is getting minified or something Prod-y. Anyway, removing it fixes the problem. 👍

**Comment by fiattt** [comment]
it works 👍

**Comment by mmoutenot** [comment]
Hard to debug - if anyone can figure out how to log while in release mode, it would be great to see what `displayName` is. I tried to put it into a `<Text/>` but didn't have enough time to see it through.

**Comment by FuYaoDe** [comment]
Awesome!!  The original react native when release `<View>`  displayName is not `View`, on ios is ``RCTView``, No wonder that could not find the reason, I just started think that the problem is because performance, so there is no animated , fortunately, only a small problem
