### ISSUE TITLE
TextInput has no pointerEvent

### ISSUE THREAD

**Issue by 1ne8ight7even** [FuYaoDe/react-native-app-intro#14]
TextInputs inside views can not be touched.

**Comment by FuYaoDe** [comment]
This problem is only happen on android device, because `ViewPagerAndroid` don't support animated, i use `absolute` hack it, and react native did't support zIndex https://github.com/facebook/react-native/issues/698, so you can slide but can't touch, maby on android you can use `onSlideChange` listen when need show TextInput or Touchable and use `absolute` hack it.

```
<View style={{ flex: 1 }}>
  <AppIntro>
    <View style={[styles.slide,{ backgroundColor: '#fa931d' }]}>
      <View level={10}><Text style={styles.text}>Page 1</Text></View>
      <View level={15}><Text style={styles.text}>Page 1</Text></View>
      <View level={8}><Text style={styles.text}>Page 1</Text></View>
    </View>
    <View style={[styles.slide, { backgroundColor: '#a4b602' }]}>
      <View level={-10}><Text style={styles.text}>Page 2</Text></View>
      <View level={5}><Text style={styles.text}>Page 2</Text></View>
      <View level={20}><Text style={styles.text}>Page 2</Text></View>
    </View>
  </AppIntro>
  <View style={{
    position: 'absolute',
    top: 100,
    left: 100,
  }}>
    <TextInput
      style={{ height: 40, width: 100 }}
    />
  </View>
</View>
```
hope facebook support zIndex soon ...

**Comment by 1ne8ight7even** [comment]
Thanks for your response. I switched to react-native-swiper. There's nor parallax, but it works for me.

**Comment by looptlinks** [comment]
Did you ever find a fix for this issue? (without the workaround)

**Comment by flobiwankenobi** [comment]
Nope, never used this plugin again. I achieved what I wanted to do with the react-native-swiper plugin.

**Comment by ariona** [comment]
Any update on this? 😄  I think i'll just use paged FlatList if it's not beed resolved

@FuYaoDe  the components inside the slide should react to every user input. In my case i have a slide that prompt some basic settings like language.

**Comment by prrenish** [comment]
https://github.com/FuYaoDe/react-native-app-intro/issues/58#issuecomment-275261038
