### ISSUE TITLE
Labels could be more than Strings

### ISSUE THREAD

**Issue by MichaelHancock** [FuYaoDe/react-native-app-intro#16]
It would be nice if we could pass actual components as params to skipBtnLabel and doneBtnLabel. Currently these take only strings which means we cannot customise them properly. For example if i wanted the font weight to be different, I should be apple to say 

`skipBtnLabel={<Text style={{fontWeight: 'normal'}}>Test</Text>}>`

This does in fact work already. As shown in the bellow example:

![simulator screen shot 22 jun 2016 10 42 04](https://cloud.githubusercontent.com/assets/10632072/16262127/45234184-3866-11e6-8643-b236e0e5cbc9.png)

As you can see the font weight has been modified... However a warning message is shown which i would rather not Force Disable.

![simulator screen shot 22 jun 2016 10 42 00](https://cloud.githubusercontent.com/assets/10632072/16262134/4a9d8886-3866-11e6-9a14-cd1e7b831bab.png)

Currently many values of the string are hardcoded, yes we can change the colour using another prop. Yet i feel it would be nice if we had more control.

**Comment by DaleJefferson** [comment]
How about

```
renderSkipBtn={() => <Text style={{fontWeight: 'normal'}}>Test</Text>}>
```

**Comment by MichaelHancock** [comment]
Yes I agree, that would be a good solution. We just need someway of better controlling the skip and done button.

**Comment by FuYaoDe** [comment]
Sorry for waiting, I've solved it in #17, I do not know it can be component XD

**Comment by iamyorchdev** [comment]
~~@FuYaoDe @MichaelHancock I'm new to react-native and have a quick question? How do you pass a component (Text) to the `doneBtnLabel` prop?~~

Forget it, I got it:

`doneBtnLabel={<Text style={{fontSize: 18}}>Test</Text>}`

**Comment by michaelsw95** [comment]
`doneBtnLabel `takes a renderable function, so something like this would work:

```
<AppIntro
  onDoneBtnClick={() => <Text>Here is some text!</Text>}
  pageArray={pageArray}
/>
```

**Comment by iamyorchdev** [comment]
Well, it worked with:
`doneBtnLabel={<Text style={{fontSize: 18}}>Test</Text>}`
what's the difference?
