### ISSUE TITLE
Add a `defaultSlide` property so the slider can play nicely with redux

### ISSUE THREAD

**Issue by chandlervdw** [FuYaoDe/react-native-app-intro#18]
If any of the callback functions manipulate the state, ie `onSlideChange`, the whole view is rerendered and the slider starts at 0. Adding a `defaultSlide` or `defaultIndex` would allow for the state to manage which slide is shown.

**Comment by jstoeffler** [comment]
Could you publish a new version with this feature? 
The `defaultIndex` is documented but not working, it's confusing :)

**Comment by FuYaoDe** [comment]
Sorry, I forgot now updated
