### ISSUE TITLE
leftTextColor doesn't do anything.

### ISSUE THREAD

**Issue by joshuapinter** [FuYaoDe/react-native-app-intro#26]
Setting the `leftTextColor` prop color has no effect.

`rightTextColor` works just fine.

**Comment by joshuapinter** [comment]
:thumbsup:

**Comment by pavlelekic** [comment]
I have the same problem on version 1.1.5, also rightTextColor sets color to both left and right text, so there is no option to have a different colors for two buttons.

**Comment by joshuapinter** [comment]
@pavlelekic With this PR request merged in you should be able to set the `leftTextColor` prop just fine. Try pulling from `master` in your `package.json` file and see if that works.

@FuYaoDe Any idea if you updated the latest npm package with this improvement?

**Comment by FuYaoDe** [comment]
Before some time there are refactoring, there may reopen this issue, but some people have made PR #47 fix it.
