### ISSUE TITLE
TypeError: Cannot assign to read only property 'onScroll' of object '#<Object>'(…)

### ISSUE THREAD

**Issue by saas-plat** [FuYaoDe/react-native-app-intro#4]
TypeError: Cannot assign to read only property 'onScroll' of object '#<Object>'(…)

  for(let prop in props) {
      // if(~scrollResponders.indexOf(prop)
      if(typeof props[prop] === 'function'
        && prop !== 'onMomentumScrollEnd'
        && prop !== 'renderPagination'
        && prop !== 'onScrollBeginDrag'
          **&& prop !== 'onScroll'**
      ) {
        let originResponder = props[prop]
        props[prop] = (e) => originResponder(e, this.state, this)
      }
    }

**Comment by FuYaoDe** [comment]
Can you give me more details? Android、ios ? react-native version、component version
and caused error sample code

**Comment by FuYaoDe** [comment]
I guess you use your react-native-swiper ?  in the react-native-app-intro  i use my custom [FuYaoDe/react-native-swiper](https://github.com/FuYaoDe/react-native-swiper)

**Comment by saas-plat** [comment]
in FuYaoDe/react-native-swiper/src/index.js

injectState method no  **&& prop !== 'onScroll'** so throw this exception

**Comment by FuYaoDe** [comment]
This message is not enough to debug, on my device is not have this error

**Comment by saas-plat** [comment]
我给你回中文啦，很少用英文

报错在这句话说
props[prop] = (e) => originResponder(e, this.state, this)

我加了一个判断就好了
 prop !== 'onScroll'

你确定，你本地的代码FuYaoDe/react-native-swiper和github上的一致吗？

**Comment by FuYaoDe** [comment]
喔喔 我知道了 你的  react-native-app-intro 版本是 1.0.2 對吧？ 升到 1.1.0 就 ok 了，因為舊版的 intro 沒有指定 swiper 版本，所以舊版的會用新版本的 swiper ，所以才會報這個錯誤

**Comment by FuYaoDe** [comment]
fix https://github.com/FuYaoDe/react-native-swiper/pull/4
