### ISSUE TITLE
The renderDoneButton prop doesn't work

### ISSUE THREAD

**Issue by zsf513** [FuYaoDe/react-native-app-intro#40]
When I set the renderSkipButton={false} ,the skipBtnLabel still works.The following is my code:
<AppIntro skipBtnLabel="跳过" 
                 skipBtnLabel={false}>
......

Why the renderSkipButton does work?

**Comment by nelsonkam** [comment]
Hello, @zsf513 the issue you are facing is due to a mistake in the documentation (actually corrected by this pending [pull request](https://github.com/FuYaoDe/react-native-app-intro/pull/37)). Instead of `renderSkipButton` and `renderDoneButton` use `showSkipButton` and `showDoneButton`.

Cheers !
