### ISSUE TITLE
No dots, skip or done buttons in both examples

### ISSUE THREAD

**Issue by nbastoWM** [FuYaoDe/react-native-app-intro#41]
Hi.
I tried both the Basic and Advanced examples but the skip, next and done buttons don't show, as well as the dots. I can only swipe (both Android and iOS).
Am I missing something?
I'm on RN 0.33.

**Comment by nbastoWM** [comment]
Hi again, 
I tried forcing all the props showSkipButton, showDots, showDoneButton to true, setting the nextBtnLabel, doneBtnLabel, skipBtnLabel, but there's no way I can see the bottom buttons. I tried with small texts on Android, iPhone 4 to iPhone 6, simulator and real devices, but with no success.

Maybe it isn't compatible with RN 0.33?

![image](https://cloud.githubusercontent.com/assets/15138821/19184523/80cf548a-8c75-11e6-83e0-907bc44d8f55.png)

**Comment by FuYaoDe** [comment]
I have seen you using Navigator
Is marginTop the reason?

**Comment by nbastoWM** [comment]
That was it!
Thank you so much!

**Comment by sfratini** [comment]
@nbastoWM  Hi! I am having the same issue. Could you please post how you fixed it? I cannot find where to modify the marginTop. Thanks!
Edit: Nevermind, I ended disabling the Navigator and it worked.
