### ISSUE TITLE
Remove or Style Dots

### ISSUE THREAD

**Issue by mshaaban0** [FuYaoDe/react-native-app-intro#44]
Hi There,

I am trying to remove the dots at the bottom of the screen or even style it. is that doable ?

<img width="373" alt="app-into-dots" src="https://cloud.githubusercontent.com/assets/6163988/19312917/337149d8-909d-11e6-9025-b68bed86e6cf.png">

Thanks

**Comment by FuYaoDe** [comment]
Hi @mshaaban0 
You can use `showDots: false`  props hide bottom dot, sorry about that forget to write on README.
By the way,  Your intro so beautiful app store can be download?

**Comment by FuYaoDe** [comment]
And there are more advanced usage, but I have not finished the document.
you can use `customStyles` props custom all style like:
```
<AppIntro
    customStyles={{
       dotStyle: {...},
       activeDotStyle: {...},
       dotContainer: {...},
    }}
/>
```

**Comment by mshaaban0** [comment]
Hi @FuYaoDe 

Thanks for the help.
Actually it's still under development, will try to update the issue once it's live :)
